package finalproject;

// import file reading librairies
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * This class creates a game over screen, displaying the time the user took,
 * their best time, a list of previous times, and buttons to replay and return
 * to the title screen
 *
 */
public class frmGameEndScreen extends javax.swing.JFrame {

    // declare variables for the previously played game
    int tileSize;
    int numRows;
    int numCols;
    int numMines;
    int fontSize;

    // declare an instance of GameBoard class
    GameBoard gameBoardInstance;

    /**
     * This creates a new game end screen JFrame
     *
     * @param tileSize
     * @param numRows
     * @param numCols
     * @param numMines
     * @param fontSize
     * @param gameBoardInstance
     * @param time
     */
    public frmGameEndScreen(int tileSize, int numRows, int numCols, int numMines, int fontSize, GameBoard gameBoardInstance, int time) {
        initComponents();

        // initialize parameters of last played game
        this.gameBoardInstance = gameBoardInstance;
        this.tileSize = tileSize;
        this.numRows = numRows;
        this.numCols = numCols;
        this.numMines = numMines;
        this.fontSize = fontSize;

        // set the time of previous game
        lblTimeTakenOutput.setText(String.valueOf(time));

        // Display sorted times from file
        displaySortedTimes();
    }

    /**
     * This method reads times from times.txt and displays them in order.
     */
    private void displaySortedTimes() {
        // declare a new integer arrayList
        List<Integer> times = new ArrayList<>();

        // try reading the text file with times
        try (BufferedReader reader = new BufferedReader(new FileReader("times.txt"))) {
            String line;
            while ((line = reader.readLine()) != null) {
                times.add(Integer.parseInt(line));
            }
        } catch (Exception e) {
        }

        // Sort times in ascending order
        Collections.sort(times);

        // Display sorted times in the textarea
        StringBuilder sb = new StringBuilder();
        for (int time : times) {
            // add the time
            sb.append(time).append(" sec\n");
        }

        // set text area text
        txaTimesList.setText(sb.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTimeTaken = new javax.swing.JLabel();
        pnlSeperator = new javax.swing.JPanel();
        lblLeaderboard = new javax.swing.JLabel();
        lblTimeTakenOutput = new javax.swing.JLabel();
        btnPlayAgain = new javax.swing.JButton();
        lblGameOver = new javax.swing.JLabel();
        btnReturnMenu = new javax.swing.JButton();
        lblSec1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaTimesList = new javax.swing.JTextArea();
        lblBorder = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        lblTimeTaken.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        lblTimeTaken.setForeground(new java.awt.Color(204, 204, 204));
        lblTimeTaken.setText("Time Taken:");

        javax.swing.GroupLayout pnlSeperatorLayout = new javax.swing.GroupLayout(pnlSeperator);
        pnlSeperator.setLayout(pnlSeperatorLayout);
        pnlSeperatorLayout.setHorizontalGroup(
            pnlSeperatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pnlSeperatorLayout.setVerticalGroup(
            pnlSeperatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblLeaderboard.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        lblLeaderboard.setForeground(new java.awt.Color(204, 204, 204));
        lblLeaderboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLeaderboard.setText("Leaderboard");

        lblTimeTakenOutput.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        lblTimeTakenOutput.setForeground(new java.awt.Color(204, 204, 204));
        lblTimeTakenOutput.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTimeTakenOutput.setText("0.00");
        lblTimeTakenOutput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        btnPlayAgain.setBackground(new java.awt.Color(51, 51, 255));
        btnPlayAgain.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        btnPlayAgain.setForeground(new java.awt.Color(204, 204, 204));
        btnPlayAgain.setText("Play Again");
        btnPlayAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayAgainActionPerformed(evt);
            }
        });

        lblGameOver.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        lblGameOver.setForeground(new java.awt.Color(204, 204, 204));
        lblGameOver.setText("GAME OVER!");

        btnReturnMenu.setBackground(new java.awt.Color(51, 51, 255));
        btnReturnMenu.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        btnReturnMenu.setForeground(new java.awt.Color(204, 204, 204));
        btnReturnMenu.setText("Return to Menu");
        btnReturnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnMenuActionPerformed(evt);
            }
        });

        lblSec1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        lblSec1.setForeground(new java.awt.Color(204, 204, 204));
        lblSec1.setText("sec");

        txaTimesList.setEditable(false);
        txaTimesList.setColumns(20);
        txaTimesList.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txaTimesList.setRows(5);
        jScrollPane1.setViewportView(txaTimesList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnReturnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPlayAgain, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblGameOver)
                                .addGap(62, 62, 62))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTimeTaken)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTimeTakenOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSec1)
                                .addGap(18, 18, 18)))))
                .addComponent(pnlSeperator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblLeaderboard, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSeperator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblGameOver)
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblTimeTakenOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblSec1))
                            .addComponent(lblTimeTaken))
                        .addGap(65, 65, 65)
                        .addComponent(btnPlayAgain)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReturnMenu)
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblLeaderboard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 460, 300));

        lblBorder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/background1Retro.PNG"))); // NOI18N
        getContentPane().add(lblBorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This closes the previous game screen and the game end screen and opens
     * the title screen when Return to Menu button is clicked
     *
     * @param evt
     */
    private void btnReturnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnMenuActionPerformed
        // close previous game screen and this screen
        gameBoardInstance.frmGame.dispose();
        this.dispose();

        // open title screen
        new frmTitleScreen().setVisible(true);

    }//GEN-LAST:event_btnReturnMenuActionPerformed

    /**
     * This closes the game end screen and resets the previous game and its
     * screen
     *
     * @param evt
     */
    private void btnPlayAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayAgainActionPerformed
        // close the previous game and restart it
        gameBoardInstance.frmGame.dispose();
        new GameBoard(numRows, numCols, numMines, tileSize, fontSize);

        // close this screen
        this.dispose();
    }//GEN-LAST:event_btnPlayAgainActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGameEndScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGameEndScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGameEndScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGameEndScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // make this screen visible using default parameters
                new frmGameEndScreen(1, 1, 1, 1, 1, null, 1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlayAgain;
    private javax.swing.JButton btnReturnMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBorder;
    private javax.swing.JLabel lblGameOver;
    private javax.swing.JLabel lblLeaderboard;
    private javax.swing.JLabel lblSec1;
    private javax.swing.JLabel lblTimeTaken;
    private javax.swing.JLabel lblTimeTakenOutput;
    private javax.swing.JPanel pnlSeperator;
    private javax.swing.JTextArea txaTimesList;
    // End of variables declaration//GEN-END:variables
}
