/**
 * This program creates a Minesweeper game that tracks and displays
 * a number of randomly generated mines around a clicked tile.
 */
package finalproject;

/**
 * This class creates a title screen for the Minesweeper game, and allows the
 * user to choose their difficulty, go to the instructions screen, play the
 * game, and exit the program
 */
public class frmTitleScreen extends javax.swing.JFrame {

    /**
     * Creates new form frmTitleScreen
     */
    public frmTitleScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        lblDifficulty = new javax.swing.JLabel();
        cmbDifficultySelection = new javax.swing.JComboBox<>();
        btnPlay = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblMainTitle = new javax.swing.JLabel();
        pnlSideBar = new javax.swing.JPanel();
        btnExitMain = new javax.swing.JButton();
        btnInstructions = new javax.swing.JButton();
        pnlBorder = new javax.swing.JPanel();
        lblBorder = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBackground.setBackground(new java.awt.Color(51, 51, 255));
        pnlBackground.setForeground(new java.awt.Color(51, 51, 255));

        lblDifficulty.setFont(new java.awt.Font("Monospac821 BT", 1, 24)); // NOI18N
        lblDifficulty.setForeground(new java.awt.Color(255, 255, 255));
        lblDifficulty.setText("Difficulty");

        cmbDifficultySelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Easy(8x8)", "Medium (12x12)", "Hard (15x15)", "Impossible (20x20)" }));
        cmbDifficultySelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDifficultySelectionActionPerformed(evt);
            }
        });

        btnPlay.setContentAreaFilled(false);
        btnPlay.setFocusPainted(false);
        btnPlay.setOpaque(false);
        btnPlay.setBackground(new java.awt.Color(0, 204, 0));
        btnPlay.setBorderPainted(false);
        btnPlay.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        btnPlay.setForeground(new java.awt.Color(255, 255, 255));
        btnPlay.setText("> Play");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        lblMainTitle.setBackground(new java.awt.Color(0, 0, 0));
        lblMainTitle.setFont(new java.awt.Font("Monospac821 BT", 0, 36)); // NOI18N
        lblMainTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblMainTitle.setText("MINESWEEPER");

        pnlSideBar.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlSideBarLayout = new javax.swing.GroupLayout(pnlSideBar);
        pnlSideBar.setLayout(pnlSideBarLayout);
        pnlSideBarLayout.setHorizontalGroup(
            pnlSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );
        pnlSideBarLayout.setVerticalGroup(
            pnlSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnExitMain.setContentAreaFilled(false);
        btnExitMain.setFocusPainted(false);
        btnExitMain.setOpaque(false);
        btnExitMain.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        btnExitMain.setForeground(new java.awt.Color(255, 255, 255));
        btnExitMain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/exit.png"))); // NOI18N
        btnExitMain.setText("Exit");
        btnExitMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitMainActionPerformed(evt);
            }
        });

        btnInstructions.setContentAreaFilled(false);
        btnInstructions.setFocusPainted(false);
        btnInstructions.setOpaque(false);
        btnInstructions.setBackground(new java.awt.Color(255, 204, 51));
        btnInstructions.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        btnInstructions.setForeground(new java.awt.Color(255, 255, 255));
        btnInstructions.setText("> Instructions");
        btnInstructions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstructionsActionPerformed(evt);
            }
        });

        pnlBorder.setLayout(null);

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInstructions)
                    .addComponent(btnExitMain)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                                .addComponent(lblMainTitle)
                                .addGap(0, 0, 0)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbDifficultySelection, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDifficulty))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 285, Short.MAX_VALUE)
                                .addComponent(pnlBorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(51, 51, 51))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMainTitle)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(lblDifficulty)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbDifficultySelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(pnlBorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExitMain, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addComponent(pnlSideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(pnlBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 520, 320));

        lblBorder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/background1Retro.PNG"))); // NOI18N
        getContentPane().add(lblBorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This opens the instructions menu screen on instructions button click
     *
     * @param evt
     */
    private void btnInstructionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstructionsActionPerformed
        // create Instructions screen
        new frmInstructionsScreen().setVisible(true);
        // close this screen
        this.dispose();

    }//GEN-LAST:event_btnInstructionsActionPerformed

    /**
     * This closes the entire program when exit button clicked
     *
     * @param evt
     */
    private void btnExitMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitMainActionPerformed
        //close program
        System.exit(0);
    }//GEN-LAST:event_btnExitMainActionPerformed

    /**
     * This runs the GameBoard class on play button clicked. It passes
     * parameters for the number of rows and columns of the Minesweeper game,
     * the number of mines to be placed, the size of each button in the grid,
     * and the font size of the text displayed in the buttons
     *
     * @param evt
     */
    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed

        // close this screen
        this.dispose();

        // create a 8 by 8 grid with 10 mines
        if (cmbDifficultySelection.getSelectedItem() == "Easy(8x8)") {
            new GameBoard(8, 8, 10, 100, 45);
        } // create a 12 by 12 grid with 20 mines
        else if (cmbDifficultySelection.getSelectedItem() == "Medium (12x12)") {
            new GameBoard(12, 12, 20, 65, 35);
        } // create a 15 by 15 grid with 50 mines
        else if (cmbDifficultySelection.getSelectedItem() == "Hard (15x15)") {
            new GameBoard(15, 15, 50, 55, 25);
        } // create a 20 by 20 grid with 100 mines
        else if (cmbDifficultySelection.getSelectedItem() == "Impossible (20x20)") {
            new GameBoard(20, 20, 100, 40, 15);
        }

    }//GEN-LAST:event_btnPlayActionPerformed

    private void cmbDifficultySelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDifficultySelectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDifficultySelectionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTitleScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTitleScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTitleScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTitleScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // make this screen visible
                new frmTitleScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExitMain;
    private javax.swing.JButton btnInstructions;
    private javax.swing.JButton btnPlay;
    private javax.swing.JComboBox<String> cmbDifficultySelection;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblBorder;
    private javax.swing.JLabel lblDifficulty;
    private javax.swing.JLabel lblMainTitle;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlBorder;
    private javax.swing.JPanel pnlSideBar;
    // End of variables declaration//GEN-END:variables
}
